List
SiansandaTamara/To-Do pull request #1
Opened 2022-05-05 01:11 UTC by SiansandaTamara

##implemented the following
-Add webpack file
-Add linter packages
-Add git flow
-Use of html/css.js
-Add button
-update reademe file
-Active the add and remove button"

2022-05-05 02:52 UTC, MahmoudBakr23 approved these changes
Hi @SiansandaTamara 😃, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! 🎉 

**Highlights**
- Well done implementing the add, remove and drag functions
- Correct Linters
- Descriptive PR

**Optional**
- Kindly make sure to do the below comments for a professional README.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-05 02:52 UTC, MahmoudBakr23 commented on README.md
> +![screenshot]()
- [ ] It seems you forgot to edit the standard empty README file. Please make sure to do so and add a valid image of the app.

2022-05-05 02:52 UTC, MahmoudBakr23 commented on README.md
> +To get a local copy up and running follow these simple example steps.
- [ ] You should add correct structures to install the app as well.

2022-05-05 02:52 UTC, MahmoudBakr23 commented on README.md
> +Feel free to check the [issues page](../../issues/).
- [ ] Please fix the issues page link.

2022-05-05 02:52 UTC, MahmoudBakr23 commented on README.md
> +This project is [MIT](./MIT.md) licensed.
- [ ] Please fix the MIT link.

2022-05-05 02:57 UTC, SiansandaTamara commented
Thank you I 'll do the needful it's only that I didn't sleep the whole night trying to work on it.Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Mahmoud Bakr ***@***.***> Date: 05/05/2022  04:52  (GMT+02:00) To: SiansandaTamara/To-Do ***@***.***> Cc: tamara siansanda ***@***.***>, Mention ***@***.***> Subject: Re: [SiansandaTamara/To-Do] List (PR #1) 

@MahmoudBakr23 approved this pull request.



Hi @SiansandaTamara 😃,

Your project is complete!  There is nothing else to say other than... it's time to merge it 

Congratulations! 🎉

Highlights



Well done implementing the add, remove and drag functions

Correct Linters

Descriptive PR



Optional



Kindly make sure to do the below comments for a professional README.



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.



As described in the Code reviews limits policy you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this form.



In README.md:

> \ No newline at end of file

+# To-Do

+

+![](https://img.shields.io/badge/Microverse-blueviolet)

+

+> This a group work project testing basic Javascript skills.

+

+# WORKFLOW SCREENSHOT

+![screenshot]()





 It seems you forgot to edit the standard empty README file. Please make sure to do so and add a valid image of the app.









In README.md:

> +

+To get a local copy up and running follow these simple example steps.





 You should add correct structures to install the app as well.









In README.md:

> +```bash

+git clone// https://github.com/SiansandaTamara/todo

+

+

+

+## Authors

+👤 **Tamara Siansanda**

+

+- GitHub: ***@***.***(https://github.com/SiansandaTamara)

+- Twitter: ***@***.***(https://twitter.com/TamaraSiansanda)

+

+## 🤝 Contributing

+

+Contributions, issues, and feature requests are welcome!

+

+Feel free to check the [issues page](../../issues/).





 Please fix the issues page link.









In README.md:

> +

+Feel free to check the [issues page](../../issues/).

+

+## Show your support

+

+Give a ⭐️ if you like this project!

+

+## Acknowledgments

+

+- Hat tip to anyone whose code was used

+- Inspiration

+- etc

+

+## 📝 License

+

+This project is [MIT](./MIT.md) licensed.





 Please fix the MIT link.





—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

[

{

***@***.***": "http://schema.org",

***@***.***": "EmailMessage",

"potentialAction": {

***@***.***": "ViewAction",

"target": "https://github.com/SiansandaTamara/To-Do/pull/1#pullrequestreview-962814807",

"url": "https://github.com/SiansandaTamara/To-Do/pull/1#pullrequestreview-962814807",

"name": "View Pull Request"

},

"description": "View this Pull Request on GitHub",

"publisher": {

***@***.***": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

2022-05-05 03:07 UTC, Meltrust requested changes
Hi @SiansandaTamara,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!



### To highlight:

- Nice styling!✔️ 

![You can do it](https://media.giphy.com/media/FemTGpEZeK27M5fKL4/giphy.gif)

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-05 03:07 UTC, Meltrust commented on package.json
> +{
- According to the project requirements:

![image](https://user-images.githubusercontent.com/57421823/166856533-1528aa5b-9eda-4cb1-81a5-5d09310ed183.png)

Therefore:

- [ ] Please, ensure that:

- Basic commands for building Webpack in development mode, production mode is configured
- Webpack dev server is set up and running with no errors.

## Explanation

This project should not be run with the "live server" VsCode extension.  This project should be run with the command "npm start".  Also, there should be a way to run the project in "watch" and "production" modes.  You will need to configure webpack and package.json for this.

## Hints

- Add this "scripts" section to your package.json:

![image](https://user-images.githubusercontent.com/57421823/166856833-d1b12788-52da-49c3-a35b-c5d22d710fca.png)

- Install the webpack dev server, CLI, Html plugin, and CSS loader:

```bash
npm install webpack-dev-server --save-dev
npm install -D webpack-cli
npm install --save-dev style-loader
npm install css-loader -D
npm install html-webpack-plugin
```

- Use this webpack config:

```javascript
const path = require('path');
const HtmlWebpackPlugin = require('html-webpack-plugin');

module.exports = {
  mode: 'development',
  entry: './src/index.js',
  devtool: 'inline-source-map',
  devServer: {
    static: './dist',
  },
  plugins: [
    new HtmlWebpackPlugin({
      template: './src/index.html',
    }),
  ],
  output: {
    filename: 'main.js',
    path: path.resolve(__dirname, 'dist'),
  },
  module: {
    rules: [
      {
        test: /\.css$/i,
        use: ['style-loader', 'css-loader'],
      },
    ],
  },
};
```
- [ ] OPTIONAL: I highly suggest getting rid of the hundreds of unnecessary dependencies your project has.

2022-05-06 15:49 UTC, andersonlebon approved these changes
Hi @SiansandaTamara 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 :clap: :clap: :100: 

![nodding-yes](https://user-images.githubusercontent.com/65068771/143095390-344d1cb0-b853-4b91-8662-5d9049dc9e60.gif)

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Good PR description :heavy_check_mark: 
- Your README file is now professional :heavy_check_mark: 

## Optional suggestions
- [ ] Kindly Check the comments under the review._
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-05-06 15:50 UTC, andersonlebon commented
[ OPTIONAL ] I suggest you add in your` README.md` file commands on how to install dependencies and run the app.

2022-05-06 15:57 UTC, merged